// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book_specs.sql

package dbgen

import (
	"context"
)

const deleteBookSpec = `-- name: DeleteBookSpec :exec
DELETE FROM book_specs WHERE project_id = ?
`

func (q *Queries) DeleteBookSpec(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookSpec, projectID)
	return err
}

const getBookSpec = `-- name: GetBookSpec :one
SELECT id, project_id, data, created_at, updated_at
FROM book_specs WHERE project_id = ?
`

func (q *Queries) GetBookSpec(ctx context.Context, projectID int64) (BookSpec, error) {
	row := q.db.QueryRowContext(ctx, getBookSpec, projectID)
	var i BookSpec
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBookSpec = `-- name: UpsertBookSpec :one
INSERT INTO book_specs (project_id, data, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(project_id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP
RETURNING id, project_id, data, created_at, updated_at
`

type UpsertBookSpecParams struct {
	ProjectID int64
	Data      string
}

func (q *Queries) UpsertBookSpec(ctx context.Context, arg UpsertBookSpecParams) (BookSpec, error) {
	row := q.db.QueryRowContext(ctx, upsertBookSpec, arg.ProjectID, arg.Data)
	var i BookSpec
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
