// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book_outputs.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createBookOutput = `-- name: CreateBookOutput :one
INSERT INTO book_outputs (
    book_id, output_format, output_data, source_filename, spec_snapshot, corrections_snapshot
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, book_id, output_format, output_data, source_filename, spec_snapshot, corrections_snapshot, created_at
`

type CreateBookOutputParams struct {
	BookID              int64
	OutputFormat        string
	OutputData          []byte
	SourceFilename      string
	SpecSnapshot        sql.NullString
	CorrectionsSnapshot sql.NullString
}

type CreateBookOutputRow struct {
	ID                  int64
	BookID              int64
	OutputFormat        string
	OutputData          []byte
	SourceFilename      string
	SpecSnapshot        sql.NullString
	CorrectionsSnapshot sql.NullString
	CreatedAt           time.Time
}

func (q *Queries) CreateBookOutput(ctx context.Context, arg CreateBookOutputParams) (CreateBookOutputRow, error) {
	row := q.db.QueryRowContext(ctx, createBookOutput,
		arg.BookID,
		arg.OutputFormat,
		arg.OutputData,
		arg.SourceFilename,
		arg.SpecSnapshot,
		arg.CorrectionsSnapshot,
	)
	var i CreateBookOutputRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.OutputFormat,
		&i.OutputData,
		&i.SourceFilename,
		&i.SpecSnapshot,
		&i.CorrectionsSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getBookOutput = `-- name: GetBookOutput :one
SELECT id, book_id, output_format, output_data, source_filename, spec_snapshot, corrections_snapshot, created_at
FROM book_outputs
WHERE id = ? AND book_id = ?
`

type GetBookOutputParams struct {
	ID     int64
	BookID int64
}

type GetBookOutputRow struct {
	ID                  int64
	BookID              int64
	OutputFormat        string
	OutputData          []byte
	SourceFilename      string
	SpecSnapshot        sql.NullString
	CorrectionsSnapshot sql.NullString
	CreatedAt           time.Time
}

func (q *Queries) GetBookOutput(ctx context.Context, arg GetBookOutputParams) (GetBookOutputRow, error) {
	row := q.db.QueryRowContext(ctx, getBookOutput, arg.ID, arg.BookID)
	var i GetBookOutputRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.OutputFormat,
		&i.OutputData,
		&i.SourceFilename,
		&i.SpecSnapshot,
		&i.CorrectionsSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listBookOutputs = `-- name: ListBookOutputs :many
SELECT id, book_id, output_format, source_filename, length(output_data) AS size_bytes, spec_snapshot, corrections_snapshot, created_at
FROM book_outputs
WHERE book_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListBookOutputsParams struct {
	BookID int64
	Limit  int64
}

type ListBookOutputsRow struct {
	ID                  int64
	BookID              int64
	OutputFormat        string
	SourceFilename      string
	SizeBytes           sql.NullInt64
	SpecSnapshot        sql.NullString
	CorrectionsSnapshot sql.NullString
	CreatedAt           time.Time
}

func (q *Queries) ListBookOutputs(ctx context.Context, arg ListBookOutputsParams) ([]ListBookOutputsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookOutputs, arg.BookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookOutputsRow
	for rows.Next() {
		var i ListBookOutputsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.OutputFormat,
			&i.SourceFilename,
			&i.SizeBytes,
			&i.SpecSnapshot,
			&i.CorrectionsSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
