// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package dbgen

import (
	"context"
	"time"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, series, source_filename, source_data, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'uploaded', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, title, author, series, source_filename, source_data, pdf_data, epub_data, status, error_msg, created_at, updated_at
`

type CreateBookParams struct {
	Title          string
	Author         string
	Series         string
	SourceFilename string
	SourceData     []byte
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Series,
		arg.SourceFilename,
		arg.SourceData,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Series,
		&i.SourceFilename,
		&i.SourceData,
		&i.PdfData,
		&i.EpubData,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, series, source_filename, source_data, pdf_data, epub_data, status, error_msg, created_at, updated_at FROM books WHERE id = ?
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Series,
		&i.SourceFilename,
		&i.SourceData,
		&i.PdfData,
		&i.EpubData,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookEPUB = `-- name: GetBookEPUB :one
SELECT id, title, epub_data FROM books WHERE id = ?
`

type GetBookEPUBRow struct {
	ID       int64
	Title    string
	EpubData []byte
}

func (q *Queries) GetBookEPUB(ctx context.Context, id int64) (GetBookEPUBRow, error) {
	row := q.db.QueryRowContext(ctx, getBookEPUB, id)
	var i GetBookEPUBRow
	err := row.Scan(&i.ID, &i.Title, &i.EpubData)
	return i, err
}

const getBookPDF = `-- name: GetBookPDF :one
SELECT id, title, pdf_data FROM books WHERE id = ?
`

type GetBookPDFRow struct {
	ID      int64
	Title   string
	PdfData []byte
}

func (q *Queries) GetBookPDF(ctx context.Context, id int64) (GetBookPDFRow, error) {
	row := q.db.QueryRowContext(ctx, getBookPDF, id)
	var i GetBookPDFRow
	err := row.Scan(&i.ID, &i.Title, &i.PdfData)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, series, source_filename, status, error_msg, created_at, updated_at
FROM books ORDER BY created_at DESC
`

type ListBooksRow struct {
	ID             int64
	Title          string
	Author         string
	Series         string
	SourceFilename string
	Status         string
	ErrorMsg       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListBooks(ctx context.Context) ([]ListBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Series,
			&i.SourceFilename,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookEPUB = `-- name: UpdateBookEPUB :exec
UPDATE books SET epub_data = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateBookEPUBParams struct {
	EpubData []byte
	ID       int64
}

func (q *Queries) UpdateBookEPUB(ctx context.Context, arg UpdateBookEPUBParams) error {
	_, err := q.db.ExecContext(ctx, updateBookEPUB, arg.EpubData, arg.ID)
	return err
}

const updateBookPDF = `-- name: UpdateBookPDF :exec
UPDATE books SET pdf_data = ?, status = 'ready', updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateBookPDFParams struct {
	PdfData []byte
	ID      int64
}

func (q *Queries) UpdateBookPDF(ctx context.Context, arg UpdateBookPDFParams) error {
	_, err := q.db.ExecContext(ctx, updateBookPDF, arg.PdfData, arg.ID)
	return err
}

const updateBookStatus = `-- name: UpdateBookStatus :exec
UPDATE books SET status = ?, error_msg = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateBookStatusParams struct {
	Status   string
	ErrorMsg string
	ID       int64
}

func (q *Queries) UpdateBookStatus(ctx context.Context, arg UpdateBookStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookStatus, arg.Status, arg.ErrorMsg, arg.ID)
	return err
}
