// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manuscript_preflights.sql

package dbgen

import (
	"context"
)

const createManuscriptPreflight = `-- name: CreateManuscriptPreflight :one
INSERT INTO manuscript_preflights (
    project_id, book_id, status, summary_json, report_json, report_html,
    error_msg, source_filename, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, project_id, book_id, status, summary_json, report_json, report_html, error_msg, source_filename, created_at, updated_at
`

type CreateManuscriptPreflightParams struct {
	ProjectID      int64
	BookID         int64
	Status         string
	SummaryJson    string
	ReportJson     string
	ReportHtml     string
	ErrorMsg       string
	SourceFilename string
}

func (q *Queries) CreateManuscriptPreflight(ctx context.Context, arg CreateManuscriptPreflightParams) (ManuscriptPreflight, error) {
	row := q.db.QueryRowContext(ctx, createManuscriptPreflight,
		arg.ProjectID,
		arg.BookID,
		arg.Status,
		arg.SummaryJson,
		arg.ReportJson,
		arg.ReportHtml,
		arg.ErrorMsg,
		arg.SourceFilename,
	)
	var i ManuscriptPreflight
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BookID,
		&i.Status,
		&i.SummaryJson,
		&i.ReportJson,
		&i.ReportHtml,
		&i.ErrorMsg,
		&i.SourceFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestManuscriptPreflight = `-- name: GetLatestManuscriptPreflight :one
SELECT id, project_id, book_id, status, summary_json, report_json, report_html, error_msg, source_filename, created_at, updated_at
FROM manuscript_preflights
WHERE project_id = ? AND book_id = ?
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetLatestManuscriptPreflightParams struct {
	ProjectID int64
	BookID    int64
}

func (q *Queries) GetLatestManuscriptPreflight(ctx context.Context, arg GetLatestManuscriptPreflightParams) (ManuscriptPreflight, error) {
	row := q.db.QueryRowContext(ctx, getLatestManuscriptPreflight, arg.ProjectID, arg.BookID)
	var i ManuscriptPreflight
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BookID,
		&i.Status,
		&i.SummaryJson,
		&i.ReportJson,
		&i.ReportHtml,
		&i.ErrorMsg,
		&i.SourceFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManuscriptPreflights = `-- name: ListManuscriptPreflights :many
SELECT id, project_id, book_id, status, summary_json, report_json, report_html, error_msg, source_filename, created_at, updated_at
FROM manuscript_preflights
WHERE project_id = ? AND book_id = ?
ORDER BY updated_at DESC, id DESC
`

type ListManuscriptPreflightsParams struct {
	ProjectID int64
	BookID    int64
}

func (q *Queries) ListManuscriptPreflights(ctx context.Context, arg ListManuscriptPreflightsParams) ([]ManuscriptPreflight, error) {
	rows, err := q.db.QueryContext(ctx, listManuscriptPreflights, arg.ProjectID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManuscriptPreflight
	for rows.Next() {
		var i ManuscriptPreflight
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BookID,
			&i.Status,
			&i.SummaryJson,
			&i.ReportJson,
			&i.ReportHtml,
			&i.ErrorMsg,
			&i.SourceFilename,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
