// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type AuthToken struct {
	ID        int64
	ProjectID int64
	TokenHash string
	Label     string
	CreatedAt time.Time
}

type Migration struct {
	MigrationNumber int64
	MigrationName   string
	ExecutedAt      time.Time
}

type Project struct {
	ID        int64
	Name      string
	StartDate string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Task struct {
	ID           int64
	ProjectID    int64
	SortOrder    int64
	Assignee     string
	Title        string
	IsMilestone  int64
	OrigWeeks    float64
	CurrWeeks    float64
	OrigDue      string
	CurrDue      string
	ActualDone   string
	Status       string
	Words        int64
	WordsPerHour int64
	Hours        float64
	Rate         float64
	BudgetNotes  string
	OrigBudget   float64
	CurrBudget   float64
	ActualBudget float64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
