// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	ID        int64
	ProjectID int64
	TokenHash string
	Label     string
	CreatedAt time.Time
}

type Book struct {
	ID             int64
	Title          string
	Author         string
	Series         string
	SourceFilename string
	SourceData     []byte
	PdfData        []byte
	EpubData       []byte
	Status         string
	ErrorMsg       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ProjectID      sql.NullInt64
}

type BookSpec struct {
	ID        int64
	ProjectID int64
	Data      string
	CreatedAt time.Time
	UpdatedAt time.Time
	CoverData []byte
	CoverType string
}

type Client struct {
	Slug         string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}

type Correction struct {
	ID          int64
	ProjectID   int64
	FindText    string
	ReplaceText string
	Chapter     sql.NullString
	Note        sql.NullString
	Status      string
	AppliedAt   sql.NullTime
	CreatedAt   time.Time
}

type FileLog struct {
	ID           int64
	ProjectID    int64
	Direction    string
	Filename     string
	FileType     string
	SentBy       string
	ReceivedBy   string
	Notes        string
	TransferDate string
	CreatedAt    time.Time
}

type Journal struct {
	ID        int64
	ProjectID int64
	EntryType string
	Content   string
	CreatedAt time.Time
}

type Migration struct {
	MigrationNumber int64
	MigrationName   string
	ExecutedAt      time.Time
}

type Project struct {
	ID          int64
	Name        string
	StartDate   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ClientSlug  string
	ProjectSlug string
	ArchivedAt  sql.NullTime
}

type Task struct {
	ID           int64
	ProjectID    int64
	SortOrder    int64
	Assignee     string
	Title        string
	IsMilestone  int64
	OrigWeeks    float64
	CurrWeeks    float64
	OrigDue      string
	CurrDue      string
	ActualDone   string
	Status       string
	Words        int64
	WordsPerHour int64
	Hours        float64
	Rate         float64
	BudgetNotes  string
	OrigBudget   float64
	CurrBudget   float64
	ActualBudget float64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Transmittal struct {
	ID        int64
	ProjectID int64
	Status    string
	Data      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TransmittalVersion struct {
	ID            int64
	TransmittalID int64
	Data          string
	Status        string
	SavedAt       time.Time
}
