// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	ID        int64
	ProjectID int64
	TokenHash string
	Label     string
	CreatedAt time.Time
}

type Book struct {
	ID             int64
	Title          string
	Author         string
	Series         string
	SourceFilename string
	SourceData     []byte
	Status         string
	ErrorMsg       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ProjectID      sql.NullInt64
}

type BookOutput struct {
	ID                  int64
	BookID              int64
	OutputFormat        string
	OutputData          []byte
	SourceFilename      string
	CreatedAt           time.Time
	SpecSnapshot        sql.NullString
	CorrectionsSnapshot sql.NullString
}

type BookSpec struct {
	ID        int64
	ProjectID int64
	Data      string
	CreatedAt time.Time
	UpdatedAt time.Time
	CoverData []byte
	CoverType string
}

type Client struct {
	Slug         string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	CohortSlug   string
}

type ContentReviewItem struct {
	ID          int64
	Batch       string
	Ord         int64
	Ref         string
	Page        string
	File        string
	Location    string
	CurrentText string
	Proposed    string
	Reason      string
	Severity    string
	Pass        int64
	Decision    string
	EditedText  string
	Note        string
	DecidedAt   sql.NullTime
	AppliedAt   sql.NullTime
	CreatedAt   time.Time
}

type Correction struct {
	ID          int64
	ProjectID   int64
	FindText    string
	ReplaceText string
	Chapter     sql.NullString
	Note        sql.NullString
	Status      string
	AppliedAt   sql.NullTime
	CreatedAt   time.Time
}

type Coupon struct {
	ID             int64
	Code           string
	Sku            string
	MaxRedemptions int64
	RedeemedCount  int64
	ExpiresAt      sql.NullTime
	RegistrationID sql.NullInt64
	IssuedToEmail  string
	Note           string
	CreatedAt      time.Time
}

type EventAnnouncement struct {
	ID             int64
	EventSlug      string
	Subject        string
	Body           string
	RecipientIds   string
	RecipientCount int64
	SentCount      int64
	FailedCount    int64
	CreatedAt      time.Time
}

type EventRegistration struct {
	ID               int64
	EventSlug        string
	Name             string
	Email            string
	Region           string
	AllSessions      int64
	Material         string
	MaterialType     string
	Background       string
	NewToProtocol    int64
	Goals            string
	ConsentEmail     int64
	Status           string
	Notes            string
	UserAgent        string
	Ip               string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	PrepStatus       string
	AttendedSessions int64
	LastEmailedAt    sql.NullTime
}

type FileLog struct {
	ID           int64
	ProjectID    int64
	Direction    string
	Filename     string
	FileType     string
	SentBy       string
	ReceivedBy   string
	Notes        string
	TransferDate string
	CreatedAt    time.Time
}

type HouseStyle struct {
	ID         int64
	SectionOrd int64
	Section    string
	ItemOrd    int64
	Kind       string
	Col1       string
	Col2       string
	Col3       string
	Body       string
	BookKind   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Journal struct {
	ID        int64
	ProjectID int64
	EntryType string
	Content   string
	CreatedAt time.Time
}

type ManuscriptPreflight struct {
	ID             int64
	ProjectID      int64
	BookID         int64
	Status         string
	SummaryJson    string
	ReportJson     string
	ReportHtml     string
	ErrorMsg       string
	SourceFilename string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Migration struct {
	MigrationNumber int64
	MigrationName   string
	ExecutedAt      time.Time
}

type OutboundEmail struct {
	ID          int64
	SentAt      time.Time
	ToAddrs     string
	CcAddrs     string
	Subject     string
	Kind        string
	RefType     string
	RefID       string
	TriggeredBy string
	StatusCode  int64
	Error       string
	Note        string
	TextBody    string
	HtmlBody    string
	BccAddrs    string
}

type Pass struct {
	ID              int64
	ProjectID       int64
	Sku             string
	Source          string
	CouponID        sql.NullInt64
	CustomerEmail   string
	CustomerName    string
	BuildsIncluded  int64
	BuildsUsed      int64
	BuildsExtra     int64
	FulfilledAt     time.Time
	ExpiresAt       time.Time
	Status          string
	Note            string
	StripeSessionID string
	AmountPaid      int64
	PromoCode       string
}

type PassLedger struct {
	ID        int64
	PassID    int64
	BookID    sql.NullInt64
	Delta     int64
	Reason    string
	CreatedAt time.Time
}

type Project struct {
	ID          int64
	Name        string
	StartDate   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ClientSlug  string
	ProjectSlug string
	ArchivedAt  sql.NullTime
}

type SitePage struct {
	ID         int64
	Route      string
	Title      string
	Owner      string
	Source     string
	Visibility string
	Listed     string
	PageType   string
	Status     string
	Note       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type SlugAlias struct {
	ID             int64
	OldClientSlug  string
	OldProjectSlug string
	NewClientSlug  string
	NewProjectSlug string
	CreatedAt      time.Time
}

type StoreOrder struct {
	ID              int64
	StripeSessionID string
	Kind            string
	PassID          sql.NullInt64
	CustomerEmail   string
	CustomerName    string
	AmountTotal     int64
	Currency        string
	PromoCode       string
	Items           string
	PaymentIntentID string
	FulfilledAt     time.Time
	Note            string
}

type StudioSetting struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type StylesheetEdit struct {
	ID         int64
	ItemID     int64
	Col1       string
	Col2       string
	Col3       string
	Body       string
	Note       string
	ProposedBy string
	ProposedAt time.Time
	State      string
}

type StylesheetItem struct {
	ID           int64
	SectionOrd   int64
	Section      string
	ItemOrd      int64
	Kind         string
	Col1         string
	Col2         string
	Col3         string
	Body         string
	Status       string
	AuthorFacing int64
	StatusBy     string
	StatusAt     sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Scope        string
}

type Task struct {
	ID           int64
	ProjectID    int64
	SortOrder    int64
	Assignee     string
	Title        string
	IsMilestone  int64
	OrigWeeks    float64
	CurrWeeks    float64
	OrigDue      string
	CurrDue      string
	ActualDone   string
	Status       string
	Words        int64
	WordsPerHour int64
	Hours        float64
	Rate         float64
	BudgetNotes  string
	OrigBudget   float64
	CurrBudget   float64
	ActualBudget float64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Transmittal struct {
	ID        int64
	ProjectID int64
	Status    string
	Data      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TransmittalVersion struct {
	ID            int64
	TransmittalID int64
	Data          string
	Status        string
	SavedAt       time.Time
}
