// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passes.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const addPassBuildsExtra = `-- name: AddPassBuildsExtra :exec
UPDATE passes SET builds_extra = builds_extra + ? WHERE id = ?
`

type AddPassBuildsExtraParams struct {
	BuildsExtra int64
	ID          int64
}

func (q *Queries) AddPassBuildsExtra(ctx context.Context, arg AddPassBuildsExtraParams) error {
	_, err := q.db.ExecContext(ctx, addPassBuildsExtra, arg.BuildsExtra, arg.ID)
	return err
}

const addPassExtras = `-- name: AddPassExtras :exec
UPDATE passes
SET builds_extra = builds_extra + ?,
    expires_at   = datetime(expires_at, ?)
WHERE id = ?
`

type AddPassExtrasParams struct {
	BuildsExtra int64
	Datetime    interface{}
	ID          int64
}

// Add-on fulfilment: more build credits and/or a longer storage window.
// months is a SQLite modifier string such as '+6 months' ('+0 months' = none).
func (q *Queries) AddPassExtras(ctx context.Context, arg AddPassExtrasParams) error {
	_, err := q.db.ExecContext(ctx, addPassExtras, arg.BuildsExtra, arg.Datetime, arg.ID)
	return err
}

const claimBookForBuild = `-- name: ClaimBookForBuild :execrows
UPDATE books SET status = 'converting', error_msg = '', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND status != 'converting'
  AND NOT EXISTS (
    SELECT 1 FROM books b
    WHERE b.project_id IS NOT NULL AND b.project_id = books.project_id
      AND b.status = 'converting' AND b.id != books.id
  )
`

// Atomically moves a book to 'converting' only if it is not already
// converting and no other book in the same project is. Backs the one-build-
// in-flight guard: two simultaneous POST /convert calls cannot both win.
func (q *Queries) ClaimBookForBuild(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimBookForBuild, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countConvertingBooksByProject = `-- name: CountConvertingBooksByProject :one
SELECT COUNT(*) FROM books WHERE project_id = ? AND status = 'converting'
`

// Backs the one-in-flight-build-per-project guard on POST /api/books/{id}/convert.
func (q *Queries) CountConvertingBooksByProject(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConvertingBooksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :one

INSERT INTO coupons (code, sku, max_redemptions, expires_at, registration_id, issued_to_email, note)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, code, sku, max_redemptions, redeemed_count, expires_at, registration_id, issued_to_email, note, created_at
`

type CreateCouponParams struct {
	Code           string
	Sku            string
	MaxRedemptions int64
	ExpiresAt      sql.NullTime
	RegistrationID sql.NullInt64
	IssuedToEmail  string
	Note           string
}

// Factory Pass: coupons, passes, and the credit ledger (migration 023).
// See docs/specs/FACTORY-PASS-API-2026-09-03.md.
func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, createCoupon,
		arg.Code,
		arg.Sku,
		arg.MaxRedemptions,
		arg.ExpiresAt,
		arg.RegistrationID,
		arg.IssuedToEmail,
		arg.Note,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Sku,
		&i.MaxRedemptions,
		&i.RedeemedCount,
		&i.ExpiresAt,
		&i.RegistrationID,
		&i.IssuedToEmail,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createPass = `-- name: CreatePass :one
INSERT INTO passes (
    project_id, sku, source, coupon_id, customer_email, customer_name,
    builds_included, expires_at, note
)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime(CURRENT_TIMESTAMP, '+6 months'), ?)
RETURNING id, project_id, sku, source, coupon_id, customer_email, customer_name, builds_included, builds_used, builds_extra, fulfilled_at, expires_at, status, note, stripe_session_id, amount_paid, promo_code, index_included
`

type CreatePassParams struct {
	ProjectID      int64
	Sku            string
	Source         string
	CouponID       sql.NullInt64
	CustomerEmail  string
	CustomerName   string
	BuildsIncluded int64
	Note           string
}

// expires_at is computed in SQL so the six-month window always matches
// fulfilled_at and uses SQLite's timestamp format.
func (q *Queries) CreatePass(ctx context.Context, arg CreatePassParams) (Pass, error) {
	row := q.db.QueryRowContext(ctx, createPass,
		arg.ProjectID,
		arg.Sku,
		arg.Source,
		arg.CouponID,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.BuildsIncluded,
		arg.Note,
	)
	var i Pass
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sku,
		&i.Source,
		&i.CouponID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BuildsIncluded,
		&i.BuildsUsed,
		&i.BuildsExtra,
		&i.FulfilledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Note,
		&i.StripeSessionID,
		&i.AmountPaid,
		&i.PromoCode,
		&i.IndexIncluded,
	)
	return i, err
}

const createPassLedgerEntry = `-- name: CreatePassLedgerEntry :exec
INSERT INTO pass_ledger (pass_id, book_id, delta, reason) VALUES (?, ?, ?, ?)
`

type CreatePassLedgerEntryParams struct {
	PassID int64
	BookID sql.NullInt64
	Delta  int64
	Reason string
}

func (q *Queries) CreatePassLedgerEntry(ctx context.Context, arg CreatePassLedgerEntryParams) error {
	_, err := q.db.ExecContext(ctx, createPassLedgerEntry,
		arg.PassID,
		arg.BookID,
		arg.Delta,
		arg.Reason,
	)
	return err
}

const createStoreOrder = `-- name: CreateStoreOrder :one
INSERT INTO store_orders (
    stripe_session_id, kind, pass_id, customer_email, customer_name,
    amount_total, currency, promo_code, items, payment_intent_id, note
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, stripe_session_id, kind, pass_id, customer_email, customer_name, amount_total, currency, promo_code, items, payment_intent_id, fulfilled_at, note
`

type CreateStoreOrderParams struct {
	StripeSessionID string
	Kind            string
	PassID          sql.NullInt64
	CustomerEmail   string
	CustomerName    string
	AmountTotal     int64
	Currency        string
	PromoCode       string
	Items           string
	PaymentIntentID string
	Note            string
}

func (q *Queries) CreateStoreOrder(ctx context.Context, arg CreateStoreOrderParams) (StoreOrder, error) {
	row := q.db.QueryRowContext(ctx, createStoreOrder,
		arg.StripeSessionID,
		arg.Kind,
		arg.PassID,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.AmountTotal,
		arg.Currency,
		arg.PromoCode,
		arg.Items,
		arg.PaymentIntentID,
		arg.Note,
	)
	var i StoreOrder
	err := row.Scan(
		&i.ID,
		&i.StripeSessionID,
		&i.Kind,
		&i.PassID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.AmountTotal,
		&i.Currency,
		&i.PromoCode,
		&i.Items,
		&i.PaymentIntentID,
		&i.FulfilledAt,
		&i.Note,
	)
	return i, err
}

const decrementPassBuildsUsed = `-- name: DecrementPassBuildsUsed :exec
UPDATE passes SET builds_used = CASE WHEN builds_used > 0 THEN builds_used - 1 ELSE 0 END
WHERE id = ?
`

func (q *Queries) DecrementPassBuildsUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, decrementPassBuildsUsed, id)
	return err
}

const findRegistrationIDByEmail = `-- name: FindRegistrationIDByEmail :one
SELECT id FROM event_registrations WHERE email = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) FindRegistrationIDByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findRegistrationIDByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, sku, max_redemptions, redeemed_count, expires_at, registration_id, issued_to_email, note, created_at FROM coupons WHERE code = ?
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Sku,
		&i.MaxRedemptions,
		&i.RedeemedCount,
		&i.ExpiresAt,
		&i.RegistrationID,
		&i.IssuedToEmail,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPass = `-- name: GetPass :one
SELECT id, project_id, sku, source, coupon_id, customer_email, customer_name, builds_included, builds_used, builds_extra, fulfilled_at, expires_at, status, note, stripe_session_id, amount_paid, promo_code, index_included FROM passes WHERE id = ?
`

func (q *Queries) GetPass(ctx context.Context, id int64) (Pass, error) {
	row := q.db.QueryRowContext(ctx, getPass, id)
	var i Pass
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sku,
		&i.Source,
		&i.CouponID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BuildsIncluded,
		&i.BuildsUsed,
		&i.BuildsExtra,
		&i.FulfilledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Note,
		&i.StripeSessionID,
		&i.AmountPaid,
		&i.PromoCode,
		&i.IndexIncluded,
	)
	return i, err
}

const getPassByProject = `-- name: GetPassByProject :one
SELECT id, project_id, sku, source, coupon_id, customer_email, customer_name, builds_included, builds_used, builds_extra, fulfilled_at, expires_at, status, note, stripe_session_id, amount_paid, promo_code, index_included FROM passes WHERE project_id = ?
`

func (q *Queries) GetPassByProject(ctx context.Context, projectID int64) (Pass, error) {
	row := q.db.QueryRowContext(ctx, getPassByProject, projectID)
	var i Pass
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sku,
		&i.Source,
		&i.CouponID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BuildsIncluded,
		&i.BuildsUsed,
		&i.BuildsExtra,
		&i.FulfilledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Note,
		&i.StripeSessionID,
		&i.AmountPaid,
		&i.PromoCode,
		&i.IndexIncluded,
	)
	return i, err
}

const getStoreOrderBySession = `-- name: GetStoreOrderBySession :one
SELECT id, stripe_session_id, kind, pass_id, customer_email, customer_name, amount_total, currency, promo_code, items, payment_intent_id, fulfilled_at, note FROM store_orders WHERE stripe_session_id = ?
`

func (q *Queries) GetStoreOrderBySession(ctx context.Context, stripeSessionID string) (StoreOrder, error) {
	row := q.db.QueryRowContext(ctx, getStoreOrderBySession, stripeSessionID)
	var i StoreOrder
	err := row.Scan(
		&i.ID,
		&i.StripeSessionID,
		&i.Kind,
		&i.PassID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.AmountTotal,
		&i.Currency,
		&i.PromoCode,
		&i.Items,
		&i.PaymentIntentID,
		&i.FulfilledAt,
		&i.Note,
	)
	return i, err
}

const incrementCouponRedeemed = `-- name: IncrementCouponRedeemed :exec
UPDATE coupons SET redeemed_count = redeemed_count + 1 WHERE id = ?
`

func (q *Queries) IncrementCouponRedeemed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementCouponRedeemed, id)
	return err
}

const incrementPassBuildsUsed = `-- name: IncrementPassBuildsUsed :exec
UPDATE passes SET builds_used = builds_used + 1 WHERE id = ?
`

func (q *Queries) IncrementPassBuildsUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementPassBuildsUsed, id)
	return err
}

const listCoupons = `-- name: ListCoupons :many
SELECT
    c.id, c.code, c.sku, c.max_redemptions, c.redeemed_count, c.expires_at,
    c.registration_id, c.issued_to_email, c.note, c.created_at,
    p.id AS pass_id, p.fulfilled_at AS redeemed_at,
    COALESCE(pr.client_slug, '') AS client_slug,
    COALESCE(pr.project_slug, '') AS project_slug,
    COALESCE(pr.name, '') AS project_name
FROM coupons c
LEFT JOIN passes p ON p.coupon_id = c.id
LEFT JOIN projects pr ON pr.id = p.project_id
ORDER BY c.created_at DESC, c.id DESC
`

type ListCouponsRow struct {
	ID             int64
	Code           string
	Sku            string
	MaxRedemptions int64
	RedeemedCount  int64
	ExpiresAt      sql.NullTime
	RegistrationID sql.NullInt64
	IssuedToEmail  string
	Note           string
	CreatedAt      time.Time
	PassID         sql.NullInt64
	RedeemedAt     sql.NullTime
	ClientSlug     string
	ProjectSlug    string
	ProjectName    string
}

func (q *Queries) ListCoupons(ctx context.Context) ([]ListCouponsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCouponsRow
	for rows.Next() {
		var i ListCouponsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Sku,
			&i.MaxRedemptions,
			&i.RedeemedCount,
			&i.ExpiresAt,
			&i.RegistrationID,
			&i.IssuedToEmail,
			&i.Note,
			&i.CreatedAt,
			&i.PassID,
			&i.RedeemedAt,
			&i.ClientSlug,
			&i.ProjectSlug,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPassLedger = `-- name: ListPassLedger :many
SELECT id, pass_id, book_id, delta, reason, created_at FROM pass_ledger WHERE pass_id = ? ORDER BY id DESC
`

func (q *Queries) ListPassLedger(ctx context.Context, passID int64) ([]PassLedger, error) {
	rows, err := q.db.QueryContext(ctx, listPassLedger, passID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PassLedger
	for rows.Next() {
		var i PassLedger
		if err := rows.Scan(
			&i.ID,
			&i.PassID,
			&i.BookID,
			&i.Delta,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPasses = `-- name: ListPasses :many
SELECT
    p.id, p.project_id, p.sku, p.source, p.coupon_id, p.customer_email,
    p.customer_name, p.builds_included, p.builds_used, p.builds_extra,
    p.fulfilled_at, p.expires_at, p.status, p.note,
    p.stripe_session_id, p.amount_paid, p.promo_code, p.index_included,
    pr.name AS project_name, pr.client_slug, pr.project_slug,
    COALESCE(c.code, '') AS coupon_code
FROM passes p
JOIN projects pr ON pr.id = p.project_id
LEFT JOIN coupons c ON c.id = p.coupon_id
ORDER BY p.fulfilled_at DESC, p.id DESC
`

type ListPassesRow struct {
	ID              int64
	ProjectID       int64
	Sku             string
	Source          string
	CouponID        sql.NullInt64
	CustomerEmail   string
	CustomerName    string
	BuildsIncluded  int64
	BuildsUsed      int64
	BuildsExtra     int64
	FulfilledAt     time.Time
	ExpiresAt       time.Time
	Status          string
	Note            string
	StripeSessionID string
	AmountPaid      int64
	PromoCode       string
	IndexIncluded   int64
	ProjectName     string
	ClientSlug      string
	ProjectSlug     string
	CouponCode      string
}

func (q *Queries) ListPasses(ctx context.Context) ([]ListPassesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPassesRow
	for rows.Next() {
		var i ListPassesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Sku,
			&i.Source,
			&i.CouponID,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.BuildsIncluded,
			&i.BuildsUsed,
			&i.BuildsExtra,
			&i.FulfilledAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Note,
			&i.StripeSessionID,
			&i.AmountPaid,
			&i.PromoCode,
			&i.IndexIncluded,
			&i.ProjectName,
			&i.ClientSlug,
			&i.ProjectSlug,
			&i.CouponCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreOrders = `-- name: ListStoreOrders :many
SELECT o.id, o.stripe_session_id, o.kind, o.pass_id, o.customer_email, o.customer_name, o.amount_total, o.currency, o.promo_code, o.items, o.payment_intent_id, o.fulfilled_at, o.note, COALESCE(pr.name, '') AS project_name,
       COALESCE(pr.client_slug, '') AS client_slug, COALESCE(pr.project_slug, '') AS project_slug
FROM store_orders o
LEFT JOIN passes p ON p.id = o.pass_id
LEFT JOIN projects pr ON pr.id = p.project_id
ORDER BY o.fulfilled_at DESC, o.id DESC
LIMIT ?
`

type ListStoreOrdersRow struct {
	ID              int64
	StripeSessionID string
	Kind            string
	PassID          sql.NullInt64
	CustomerEmail   string
	CustomerName    string
	AmountTotal     int64
	Currency        string
	PromoCode       string
	Items           string
	PaymentIntentID string
	FulfilledAt     time.Time
	Note            string
	ProjectName     string
	ClientSlug      string
	ProjectSlug     string
}

func (q *Queries) ListStoreOrders(ctx context.Context, limit int64) ([]ListStoreOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listStoreOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoreOrdersRow
	for rows.Next() {
		var i ListStoreOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.StripeSessionID,
			&i.Kind,
			&i.PassID,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.AmountTotal,
			&i.Currency,
			&i.PromoCode,
			&i.Items,
			&i.PaymentIntentID,
			&i.FulfilledAt,
			&i.Note,
			&i.ProjectName,
			&i.ClientSlug,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreOrdersForPass = `-- name: ListStoreOrdersForPass :many
SELECT id, stripe_session_id, kind, pass_id, customer_email, customer_name, amount_total, currency, promo_code, items, payment_intent_id, fulfilled_at, note FROM store_orders WHERE pass_id = ? ORDER BY fulfilled_at DESC, id DESC
`

func (q *Queries) ListStoreOrdersForPass(ctx context.Context, passID sql.NullInt64) ([]StoreOrder, error) {
	rows, err := q.db.QueryContext(ctx, listStoreOrdersForPass, passID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreOrder
	for rows.Next() {
		var i StoreOrder
		if err := rows.Scan(
			&i.ID,
			&i.StripeSessionID,
			&i.Kind,
			&i.PassID,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.AmountTotal,
			&i.Currency,
			&i.PromoCode,
			&i.Items,
			&i.PaymentIntentID,
			&i.FulfilledAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservePassBuildCredit = `-- name: ReservePassBuildCredit :execrows
UPDATE passes SET builds_used = builds_used + 1
WHERE id = ? AND builds_used < builds_included + builds_extra
`

// Debits one build credit only while the pass still has one. Zero rows
// means the pass is spent; the caller answers 402 instead of over-debiting.
func (q *Queries) ReservePassBuildCredit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, reservePassBuildCredit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCouponRegistration = `-- name: SetCouponRegistration :exec
UPDATE coupons SET registration_id = ? WHERE id = ? AND registration_id IS NULL
`

type SetCouponRegistrationParams struct {
	RegistrationID sql.NullInt64
	ID             int64
}

func (q *Queries) SetCouponRegistration(ctx context.Context, arg SetCouponRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, setCouponRegistration, arg.RegistrationID, arg.ID)
	return err
}

const setPassIndexIncluded = `-- name: SetPassIndexIncluded :exec
UPDATE passes SET index_included = 1 WHERE id = ?
`

// Back-of-book index add-on fulfilment (store "index" item or admin grant).
func (q *Queries) SetPassIndexIncluded(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setPassIndexIncluded, id)
	return err
}

const setPassPurchase = `-- name: SetPassPurchase :exec
UPDATE passes SET stripe_session_id = ?, amount_paid = ?, promo_code = ? WHERE id = ?
`

type SetPassPurchaseParams struct {
	StripeSessionID string
	AmountPaid      int64
	PromoCode       string
	ID              int64
}

// Stamps a pass with the Checkout Session that bought it (source = stripe).
func (q *Queries) SetPassPurchase(ctx context.Context, arg SetPassPurchaseParams) error {
	_, err := q.db.ExecContext(ctx, setPassPurchase,
		arg.StripeSessionID,
		arg.AmountPaid,
		arg.PromoCode,
		arg.ID,
	)
	return err
}

const updatePassStatus = `-- name: UpdatePassStatus :exec
UPDATE passes SET status = ? WHERE id = ?
`

type UpdatePassStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdatePassStatus(ctx context.Context, arg UpdatePassStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePassStatus, arg.Status, arg.ID)
	return err
}
