// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package dbgen

import (
	"context"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (project_id, token_hash, label)
VALUES (?, ?, ?)
`

type CreateAuthTokenParams struct {
	ProjectID int64
	TokenHash string
	Label     string
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken, arg.ProjectID, arg.TokenHash, arg.Label)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, start_date, client_slug, project_slug, created_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, start_date, created_at, updated_at, client_slug, project_slug, archived_at
`

type CreateProjectParams struct {
	Name        string
	StartDate   string
	ClientSlug  string
	ProjectSlug string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.StartDate,
		arg.ClientSlug,
		arg.ProjectSlug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientSlug,
		&i.ProjectSlug,
		&i.ArchivedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    project_id, sort_order, assignee, title, is_milestone,
    orig_weeks, curr_weeks, orig_due, curr_due, actual_done, status,
    words, words_per_hour, hours, rate, budget_notes,
    orig_budget, curr_budget, actual_budget,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) RETURNING id, project_id, sort_order, assignee, title, is_milestone, orig_weeks, curr_weeks, orig_due, curr_due, actual_done, status, words, words_per_hour, hours, rate, budget_notes, orig_budget, curr_budget, actual_budget, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID    int64
	SortOrder    int64
	Assignee     string
	Title        string
	IsMilestone  int64
	OrigWeeks    float64
	CurrWeeks    float64
	OrigDue      string
	CurrDue      string
	ActualDone   string
	Status       string
	Words        int64
	WordsPerHour int64
	Hours        float64
	Rate         float64
	BudgetNotes  string
	OrigBudget   float64
	CurrBudget   float64
	ActualBudget float64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.SortOrder,
		arg.Assignee,
		arg.Title,
		arg.IsMilestone,
		arg.OrigWeeks,
		arg.CurrWeeks,
		arg.OrigDue,
		arg.CurrDue,
		arg.ActualDone,
		arg.Status,
		arg.Words,
		arg.WordsPerHour,
		arg.Hours,
		arg.Rate,
		arg.BudgetNotes,
		arg.OrigBudget,
		arg.CurrBudget,
		arg.ActualBudget,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SortOrder,
		&i.Assignee,
		&i.Title,
		&i.IsMilestone,
		&i.OrigWeeks,
		&i.CurrWeeks,
		&i.OrigDue,
		&i.CurrDue,
		&i.ActualDone,
		&i.Status,
		&i.Words,
		&i.WordsPerHour,
		&i.Hours,
		&i.Rate,
		&i.BudgetNotes,
		&i.OrigBudget,
		&i.CurrBudget,
		&i.ActualBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthTokensByProject = `-- name: DeleteAuthTokensByProject :exec
DELETE FROM auth_tokens WHERE project_id = ?
`

func (q *Queries) DeleteAuthTokensByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthTokensByProject, projectID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getAuthToken = `-- name: GetAuthToken :one
SELECT id, project_id, token_hash, label, created_at FROM auth_tokens WHERE project_id = ? AND token_hash = ?
`

type GetAuthTokenParams struct {
	ProjectID int64
	TokenHash string
}

func (q *Queries) GetAuthToken(ctx context.Context, arg GetAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getAuthToken, arg.ProjectID, arg.TokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, start_date, created_at, updated_at, client_slug, project_slug, archived_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientSlug,
		&i.ProjectSlug,
		&i.ArchivedAt,
	)
	return i, err
}

const getProjectByPath = `-- name: GetProjectByPath :one
SELECT id, name, start_date, created_at, updated_at, client_slug, project_slug, archived_at FROM projects WHERE client_slug = ? AND project_slug = ? AND archived_at IS NULL
`

type GetProjectByPathParams struct {
	ClientSlug  string
	ProjectSlug string
}

func (q *Queries) GetProjectByPath(ctx context.Context, arg GetProjectByPathParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByPath, arg.ClientSlug, arg.ProjectSlug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientSlug,
		&i.ProjectSlug,
		&i.ArchivedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, sort_order, assignee, title, is_milestone, orig_weeks, curr_weeks, orig_due, curr_due, actual_done, status, words, words_per_hour, hours, rate, budget_notes, orig_budget, curr_budget, actual_budget, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SortOrder,
		&i.Assignee,
		&i.Title,
		&i.IsMilestone,
		&i.OrigWeeks,
		&i.CurrWeeks,
		&i.OrigDue,
		&i.CurrDue,
		&i.ActualDone,
		&i.Status,
		&i.Words,
		&i.WordsPerHour,
		&i.Hours,
		&i.Rate,
		&i.BudgetNotes,
		&i.OrigBudget,
		&i.CurrBudget,
		&i.ActualBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArchivedProjects = `-- name: ListArchivedProjects :many
SELECT id, name, start_date, created_at, updated_at, client_slug, project_slug, archived_at FROM projects WHERE archived_at IS NOT NULL ORDER BY archived_at DESC, updated_at DESC
`

func (q *Queries) ListArchivedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientSlug,
			&i.ProjectSlug,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthTokens = `-- name: ListAuthTokens :many
SELECT id, project_id, token_hash, label, created_at FROM auth_tokens WHERE project_id = ?
`

func (q *Queries) ListAuthTokens(ctx context.Context, projectID int64) ([]AuthToken, error) {
	rows, err := q.db.QueryContext(ctx, listAuthTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthToken
	for rows.Next() {
		var i AuthToken
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TokenHash,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, start_date, created_at, updated_at, client_slug, project_slug, archived_at FROM projects WHERE archived_at IS NULL ORDER BY updated_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientSlug,
			&i.ProjectSlug,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, project_id, sort_order, assignee, title, is_milestone, orig_weeks, curr_weeks, orig_due, curr_due, actual_done, status, words, words_per_hour, hours, rate, budget_notes, orig_budget, curr_budget, actual_budget, created_at, updated_at FROM tasks WHERE project_id = ? ORDER BY sort_order
`

func (q *Queries) ListTasks(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SortOrder,
			&i.Assignee,
			&i.Title,
			&i.IsMilestone,
			&i.OrigWeeks,
			&i.CurrWeeks,
			&i.OrigDue,
			&i.CurrDue,
			&i.ActualDone,
			&i.Status,
			&i.Words,
			&i.WordsPerHour,
			&i.Hours,
			&i.Rate,
			&i.BudgetNotes,
			&i.OrigBudget,
			&i.CurrBudget,
			&i.ActualBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name = ?, start_date = ?, client_slug = ?, project_slug = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateProjectParams struct {
	Name        string
	StartDate   string
	ClientSlug  string
	ProjectSlug string
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.StartDate,
		arg.ClientSlug,
		arg.ProjectSlug,
		arg.ID,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET
    assignee = ?, title = ?, is_milestone = ?,
    orig_weeks = ?, curr_weeks = ?,
    orig_due = ?, curr_due = ?, actual_done = ?, status = ?,
    words = ?, words_per_hour = ?, hours = ?, rate = ?,
    budget_notes = ?, orig_budget = ?, curr_budget = ?, actual_budget = ?,
    sort_order = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTaskParams struct {
	Assignee     string
	Title        string
	IsMilestone  int64
	OrigWeeks    float64
	CurrWeeks    float64
	OrigDue      string
	CurrDue      string
	ActualDone   string
	Status       string
	Words        int64
	WordsPerHour int64
	Hours        float64
	Rate         float64
	BudgetNotes  string
	OrigBudget   float64
	CurrBudget   float64
	ActualBudget float64
	SortOrder    int64
	ID           int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Assignee,
		arg.Title,
		arg.IsMilestone,
		arg.OrigWeeks,
		arg.CurrWeeks,
		arg.OrigDue,
		arg.CurrDue,
		arg.ActualDone,
		arg.Status,
		arg.Words,
		arg.WordsPerHour,
		arg.Hours,
		arg.Rate,
		arg.BudgetNotes,
		arg.OrigBudget,
		arg.CurrBudget,
		arg.ActualBudget,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
